- category: --Mauve Daily--
  songs:
  - name: Mauve/Beautiful_Mauve.opus
  - name: Mauve/Dangerous_Thinking.opus
  - name: Mauve/Days_of_Joy.opus
  - name: Mauve/Investigation_Daily_Life.opus
  - name: Mauve/Investigation_Daily.opus
  - name: Mauve/Memory.opus
  - name: Mauve/Reasons.opus
  - name: Mauve/Reversal.opus
  - name: Mauve/Room_of_Mystery.opus
  - name: Mauve/Ship.opus
  - name: Mauve/Soul_Tears.opus
  - name: Mauve/Trouble_Arises.opus
  - name: Mauve/Violaceous.opus
- category: --Mauve Deadly--
  songs:
  - name: Mauve/Closure.opus
  - name: Mauve/Cognitive_Logic.opus
  - name: Mauve/Hangman's_Ploy.opus
  - name: Mauve/Investigation.opus
  - name: Mauve/Investigation_2.0.opus
  - name: Mauve/Killer_Instict.opus
  - name: Mauve/Mauve_Climax.opus
  - name: Mauve/Mauve_Hope&Despair.opus
  - name: Mauve/Mauvesphere.opus
  - name: Mauve/Mind_Drive.opus
  - name: Mauve/Rebuttal_Showoff.opus
  - name: Mauve/Vocalize.opus
