- category: --Eden's Garden--
  songs:
  - name: dro_peg/A Brief Explanation.opus
  - name: dro_peg/A Shoulder To Lean On.opus
  - name: dro_peg/Argument Altercation 1st Edition - Phase 1.opus
  - name: dro_peg/Argument Altercation 1st Edition - Phase 2.opus
  - name: dro_peg/Argument Altercation 1st Edition - Phase 3.opus
  - name: dro_peg/Beautiful Creation.opus
  - name: dro_peg/Beautiful Dawn.opus
  - name: dro_peg/Beautiful Tragedy.opus
  - name: dro_peg/Beautiful Tranquility.opus
  - name: dro_peg/Body Discovery 0.opus
  - name: dro_peg/Body Discovery 1.opus
  - name: dro_peg/Broken Dawn.opus
  - name: dro_peg/Case Closed.opus
  - name: dro_peg/Class Trial - Advance.opus
  - name: dro_peg/Class Trial - Breakthrough [DEADLY REDUX].opus
  - name: dro_peg/Class Trial - Breakthrough.opus
  - name: dro_peg/Class Trial - Confessional.opus
  - name: dro_peg/Class Trial - Judgment Day.opus
  - name: dro_peg/Class Trial - On Edge.opus
  - name: dro_peg/Class Trial - Preparation.opus
  - name: dro_peg/Class Trial - Puzzle Pieces.opus
  - name: dro_peg/Class Trial - Revelation [DEADLY REDUX].opus
  - name: dro_peg/Class Trial - Revelation.opus
  - name: dro_peg/Class Trial - Unravel.opus
  - name: dro_peg/Cold Comfort.opus
  - name: dro_peg/Connecting the Dots.opus
  - name: dro_peg/Danger.opus
  - name: dro_peg/DECEIT.opus
  - name: dro_peg/Distant Twilight.opus
  - name: dro_peg/Doomsdayer.opus
  - name: dro_peg/Final Adjudication.opus
  - name: dro_peg/Fractured Mind of the Viceroy.opus
  - name: dro_peg/Gazing Upon a Scorched Horizon (Instrumental).opus
  - name: dro_peg/Gazing Upon a Scorched Horizon.opus
  - name: dro_peg/Genesis.opus
  - name: dro_peg/Grave Accusation.opus
  - name: dro_peg/Humanity's Best and Brightest.opus
  - name: dro_peg/Isolation.opus
  - name: dro_peg/Looking Forward, Stepping Back.opus
  - name: dro_peg/Looming Trial.opus
  - name: dro_peg/M.T. by Mayhem - Variation.opus
  - name: dro_peg/M.T. by Mayhem.opus
  - name: dro_peg/Malady and Tragedy - Lost.opus
  - name: dro_peg/Malady and Tragedy - Searching.opus
  - name: dro_peg/Non-Senseless.opus
  - name: dro_peg/Non-Stop Debate - Boiling Point.opus
  - name: dro_peg/Non-Stop Debate - Exigent.opus
  - name: dro_peg/Non-Stop Debate - Frenetic Edition [DEADLY REDUX].opus
  - name: dro_peg/Non-Stop Debate - Frenetic Edition.opus
  - name: dro_peg/Non-Stop Debate - Heat Up [DEADLY REDUX].opus
  - name: dro_peg/Non-Stop Debate - Heat Up.opus
  - name: dro_peg/Non-Stop Debate - Power Through.opus
  - name: dro_peg/Old World Revival.opus
  - name: dro_peg/Rebuttal Showdown.opus
  - name: dro_peg/Talk It Through, Think It Out.opus
  - name: dro_peg/Tangled Web.opus
  - name: dro_peg/Tension [DEADLY REDUX].opus
  - name: dro_peg/Tension.opus
  - name: dro_peg/The Court Jester's Smile.opus
  - name: dro_peg/The Headmaster Appears.opus
  - name: dro_peg/To What End.opus
  - name: dro_peg/Tozu's Amazing Amenities.opus
  - name: dro_peg/Trepidation.opus
  - name: dro_peg/Warm Body.opus
  - name: dro_peg/Y2K.opus
  - name: dro_peg/Fiery Furnace of Afflication.opus